# fly.toml app configuration file generated for robert-dininno-dot-com on 2024-03-07T13:20:25-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'robert-dininno-dot-com'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
